server:
  port: 8084

spring:
  profiles:
    active: local

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: net.hwyz.iov.cloud.tsp.tbox.service.infrastructure.repository.po